"
This class contains example implementation that is already part of image (defined example methods), but import should remove reference implementation, so it should fail. 
"
Class {
	#name : 'ExampleEmptySolutionClass',
	#superclass : 'Object',
	#category : 'Exercise@ExampleEmptySolutionClass',
	#package : 'Exercise@ExampleEmptySolutionClass'
}

{ #category : 'as yet unclassified' }
ExampleEmptySolutionClass >> exerciseMethodA [
	^ $A
]

{ #category : 'as yet unclassified' }
ExampleEmptySolutionClass >> exerciseMethodB [
	^ $B
]

{ #category : 'as yet unclassified' }
ExampleEmptySolutionClass >> exerciseMethodC [
	^ $C
]
