name: Pharo track CI

on:
  push:
    branches: [main]
  pull_request:


jobs:
  build:
    runs-on: ubuntu-26.04
    strategy:
      fail-fast: false
      matrix:
        smalltalk: [Pharo64-12,  Pharo64-11]
    name: ${{ matrix.smalltalk }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: hpi-swa/setup-smalltalkCI@b6a2d26f3cb2a4f2d89a99bf5658389c387c4c83
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - run: smalltalkci -s ${{ matrix.smalltalk }}
        shell: bash
        timeout-minutes: 15
