name: Pharo track CI

on:
  push:
    branches: [main]
  pull_request:


jobs:
  build:
    runs-on: ubuntu-26.04
    strategy:
      fail-fast: false
      matrix:
        smalltalk: [Pharo64-12,  Pharo64-11]
    name: ${{ matrix.smalltalk }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: hpi-swa/setup-smalltalkCI@c0a3a3b942ac515b6c3846ca2f65802d353757ef
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - run: smalltalkci -s ${{ matrix.smalltalk }}
        shell: bash
        timeout-minutes: 15
